apps/projects/urls.py
from django.urls import path
from . import views, utils
from . import ajax_datatable_views

app_name = 'projects'

urlpatterns = [
    path('lists', views.ProjectListView.as_view(), name='lists'),
    path('show/<str:pk>', views.ProjectDetailView.as_view(), name='show'),
    path('create', views.ProjectCreateView.as_view(), name='create'),
    path('<str:pk>/edit', views.ProjectUpdateView.as_view(), name='edit'),
    path("<str:pk>/delete-confirm/", views.ProjectDeleteConfirmView.as_view(), name="delete-confirm"),
    path('<str:pk>/delete', views.ProjectDeleteView.as_view(), name='delete'),
    path('<str:pk>/activate', views.ProjectActivateView.as_view(), name='activate'),
    path('<str:pk>/data', views.ProjectDataView.as_view(), name='data'),

    # project members
    path('<str:pk>/members', views.ProjectMembersListView.as_view(), name='members'),

    # form management
    path('forms/<str:pk>', views.SurveyListView.as_view(), name='forms'),
    path('forms/<str:pk>/upload', views.SurveyCreateView.as_view(), name='upload-form'),
    path('forms/<str:pk>/edit', views.SurveyUpdateView.as_view(), name='edit-form'),
    path('forms/<str:pk>/delete', views.SurveyDeleteView.as_view(), name='delete-form'),
    path("forms/<str:pk>/definition", views.form_definition, name="form-definition"),

    # rules + OHKR
    path('forms/<str:pk>/attachments', views.SurveyAttachmentView.as_view(), name='form-attachments'),
    path('forms/<str:pk>/rules', views.SurveyRuleView.as_view(), name='form-rules'),

    # form data
    path('forms/<str:pk>/data', views.SurveyDataView.as_view(), name='form-data'),
    path('forms/<str:pk>/data/export', views.SurveyDataExportView.as_view(), name="form-data-export"),
    path('forms/<str:data_id>/data/instance', views.SurveyDataInstanceView.as_view(), name="form-data-instance"),

    path('forms/<str:pk>/data/charts', views.ChartsDataView.as_view(), name='form-data-charts'),
    path('forms/<str:pk>/data/map', views.MapDataView.as_view(), name='form-data-map'),
    path("forms/<str:form_id>/data/points", views.form_points, name="form-data-point"),

    #ajax datatable views
    path('projects-datatable', ajax_datatable_views.ProjectAjaxDatatableView.as_view(), name="dt-projects"),
    path('members-datatable/<str:pk>', ajax_datatable_views.MembersAjaxDatatableView.as_view(), name="dt-members"),
    path('forms-datatable/<str:pk>', ajax_datatable_views.FormsAjaxDatatableView.as_view(), name="dt-forms"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

import apps.accounts.urls
import apps.dashboard.urls
import apps.projects.urls
import apps.ohkr.urls
import apps.api.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(apps.accounts.urls)),
    path('auth/', include(apps.accounts.urls)),
    path('dashboard/', include(apps.dashboard.urls)),
    path('projects/', include(apps.projects.urls)),
    path('ohkr/', include(apps.ohkr.urls)),

    # API URL
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path("api/", include(apps.api.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/projects/views.py
import json
import logging
import random
import string
import csv
from datetime import datetime
from datetime import datetime, date
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.utils.safestring import mark_safe

from django.db.models import Count, Sum, Avg, Max, Min
from django.db.models.functions import Cast, TruncMonth, TruncYear
from django.db.models import FloatField, IntegerField

from django.db.models.fields.json import KeyTextTransform
from datetime import date, datetime
from django.http import JsonResponse, HttpResponse
from . import x2jform
from . import utils

from .models import Project, FormDefinition, FormData
from .forms import ProjectForm, SurveyAddForm, SurveyUpdateForm, SurveyAttachmentForm
from apps.ohkr.models import ClinicalSign


class ProjectListView(generic.ListView):
    # permission_required = ''

    """Project Listing"""
    model = Project
    context_object_name = "projects"
    template_name = "projects/lists.html"
    # paginate_by = 50

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context["title"] = "Projects"
        context["page_title"] = "Projects"

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "Projects", "url": "#"},
        ]

        # Add links to context
        context["links"] = {
            "Project Lists": reverse_lazy("projects:lists"),
            "Create Project": reverse_lazy("projects:create"),
        }

        return context


class ProjectDetailView(generic.DetailView):
    # permission_required = ''

    """View details"""
    model = Project
    context_object_name = "project"
    template_name = "projects/show.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context["title"] = "Project Information"
        context["page_title"] = "Project Information"

        return context

    def get(self, request, *args, **kwargs):
        # get project
        project = Project.objects.get(pk=kwargs["pk"])

        context = {"project": project}

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "Projects", "url": reverse_lazy("projects:lists")},
            {"name": project.title, "url": ""},
        ]

        # Add links to context
        context["links"] = {
            "Information": reverse_lazy("projects:lists"),
            "Members": reverse_lazy("projects:members", kwargs={"pk": kwargs["pk"]}),
            "Forms": reverse_lazy("projects:forms", kwargs={"pk": kwargs["pk"]}),
            "Upload Form": reverse_lazy(
                "projects:upload-form", kwargs={"pk": kwargs["pk"]}
            ),
        }

        return render(request, self.template_name, context)


class ProjectCreateView(generic.CreateView):
    # permission_required = ''

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreateView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = {"title": "Create Project", "form": ProjectForm()}
        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "Projects", "url": reverse_lazy("projects:lists")},
            {"name": "Create Project", "url": "#"},
        ]

        # Add links to context
        context["links"] = {
            "Project Lists": reverse_lazy("projects:lists"),
            "Create Project": reverse_lazy("projects:create"),
        }

        return render(request, "projects/create.html", context)

    def post(self, request, *args, **kwargs):
        form = ProjectForm(request.POST)

        if form.is_valid():
            project = form.save(commit=False)
            project.code = utils.generate_unique_code(Project, "code", 5)
            project.created_by = request.user
            project.save()

            # success response
            return HttpResponse(
                '<div class="bg-teal-100 rounded-b text-teal-900 rounded-sm text-sm px-4 py-4">Project created.</div>'
            )
        else:
            # error response
            errors = []
            for field_errors in form.errors.values():
                errors.extend(field_errors)

            return HttpResponse(
                '<div class="bg-red-100 text-red-900 rounded-sm text-sm px-4 py-3">'
                + "<br>".join(errors)
                + "</div>"
            )


class ProjectUpdateView(generic.UpdateView):
    # permission_required = ''

    """View to update"""
    model = Project
    context_object_name = "project"
    template_name = "projects/edit.html"

    def get(self, request, *args, **kwargs):
        # get project
        project = Project.objects.get(pk=kwargs["pk"])
        form = ProjectForm(instance=project)

        context = {"title": project.title, "project": project, "form": form}

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "Projects", "url": reverse_lazy("projects:lists")},
            {"name": project.title, "url": "#"},
        ]

        # Add links to context
        context["links"] = {
            "Project Lists": reverse_lazy("projects:lists"),
            "Create New": reverse_lazy("projects:create"),
        }

        return render(request, "projects/edit.html", context)

    def post(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs["pk"])
        form = ProjectForm(request.POST, instance=project)

        if form.is_valid():
            project = form.save(commit=False)
            project.updated_by = request.user
            form.save()

            # success response
            return HttpResponse(
                '<div class="bg-teal-100 rounded-b text-teal-900 rounded-sm text-sm px-4 py-4">Project updated.</div>'
            )
        else:
            # error response
            errors = []
            for field_errors in form.errors.values():
                errors.extend(field_errors)

            return HttpResponse(
                '<div class="bg-red-100 text-red-900 rounded-sm text-sm px-4 py-3">'
                + "<br>".join(errors)
                + "</div>"
            )


class ProjectDeleteConfirmView(generic.DetailView):
    model = Project
    template_name = "projects/_delete_confirm_modal.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Project, pk=self.kwargs["pk"])


class ProjectDeleteView(generic.TemplateView):
    """View to delete project"""

    def get(self, request, *args, **kwargs):
        try:
            project = Project.objects.get(pk=kwargs["pk"])
            project.deleted = 1
            project.save()

            return JsonResponse(
                {"error": False, "success_msg": "Project deleted"}, status=200
            )
        except:
            return JsonResponse(
                {"error": True, "error_msg": "Failed to delete project"}, status=404
            )


class ProjectActivateView(generic.TemplateView):
    """View to activate or deactivate a project"""

    def get(self, request, *args, **kwargs):
        try:
            project = Project.objects.get(pk=kwargs["pk"])
            if project.active:
                project.active = False
            else:
                project.active = True
            project.save()

            # success response
            return HttpResponse(
                '<div class="bg-teal-100 rounded-b text-teal-900 rounded-sm text-sm px-4 py-4">Project status updated.</div>'
            )
        except:
            # error response
            return HttpResponse(
                f'<div class="bg-red-100 rounded-b text-red-900 rounded-sm text-sm px-4 py-4">Project not found</div>'
            )


class ProjectMembersListView(generic.TemplateView):
    """View to list all project members"""

    def get(self, request, *args, **kwargs):
        # get project
        project = Project.objects.get(pk=kwargs["pk"])

        context = {
            "title": "Project Members",
            "project": project,
        }

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "Projects", "url": reverse_lazy("projects:lists")},
            {"name": project.title, "url": ""},
        ]

        context["links"] = {
            "Members": reverse_lazy("projects:members", kwargs={"pk": kwargs["pk"]}),
            "Forms": reverse_lazy("projects:forms", kwargs={"pk": kwargs["pk"]}),
            "Upload Form": reverse_lazy(
                "projects:upload-form", kwargs={"pk": kwargs["pk"]}
            ),
            "Knowledge Base": "#",
            "Data": reverse_lazy("projects:data", kwargs={"pk": kwargs["pk"]}),
        }

        # render view

apps/projects/templates/surveys/data/charts.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<main class="bg-white h-full"
      x-data="chartsBuilder({
        postUrl: '{% url 'projects:form-data-charts' pk=cur_form.pk %}',
        csrfToken: '{{ csrf_token }}'
      })"
      class="min-h-screen">

  <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">

      <!-- Left: Builder / filters -->
      <aside class="lg:col-span-4">
        <div class="bg-white rounded-lg shadow-sm border border-gray-200">
          <div class="px-5 py-4 border-b border-gray-200">
            <h2 class="text-sm font-semibold text-gray-800">Chart Builder</h2>
            <p class="text-xs text-gray-500">Choose x-axis, y-axis, and aggregation.</p>
          </div>

          <div class="p-5 space-y-5">

            <!-- Chart config -->
            <div class="space-y-3">
              <div>
                <label class="block text-xs font-medium text-gray-700 mb-1">X-axis</label>
                <select x-model="form.x_axis" title="x-axis"
                        class="w-full rounded-md border-gray-300 text-sm focus:ring-indigo-500 focus:border-indigo-500">
                  <optgroup label="Form data fields">
                    <option value="form_data.wilaya">Wilaya (District)</option>
                    <option value="form_data.kata">Kata (Ward)</option>
                    <option value="form_data.sex">Sex</option>
                  </optgroup>
                </select>
              </div>

              <div>
                <label class="block text-xs font-medium text-gray-700 mb-1">Aggregate</label>
                <select x-model="form.agg" title="agg"
                        class="w-full rounded-md border-gray-300 text-sm focus:ring-indigo-500 focus:border-indigo-500">
                  <option value="count">Count</option>
                  <option value="sum">Sum</option>
                  <option value="avg">Average</option>
                  <option value="max">Max</option>
                  <option value="min">Min</option>
                </select>
              </div>

              <div x-show="form.agg !== 'count'" x-cloak>
                <label class="block text-xs font-medium text-gray-700 mb-1">Y-axis (numeric field)</label>
                <select x-model="form.y_axis" title="y-axis"
                        class="w-full rounded-md border-gray-300 text-sm focus:ring-indigo-500 focus:border-indigo-500">
                  <option value="">-- Select numeric field --</option>
                  <option value="form_data.idadi_cal">idadi_cal</option>
                  <option value="form_data.idadi_call">idadi_call</option>
                  <option value="form_data.idadi_dalili_wakubwa">idadi_dalili_wakubwa</option>
                  <option value="form_data.idadi_dalili_wadogo">idadi_dalili_wadogo</option>
                  <option value="form_data.idadi_kufa_wakubwa">idadi_kufa_wakubwa</option>
                  <option value="form_data.idadi_kufa_wadogo">idadi_kufa_wadogo</option>
                </select>
              </div>
            </div>

            <!-- Filters -->
            <div class="pt-2 border-t border-gray-100">
              <div class="flex items-center justify-between mb-2">
                <h3 class="text-xs font-semibold text-gray-700">Filters</h3>
                <button type="button"
                        @click="resetFilters()"
                        class="text-xs text-gray-500 hover:text-gray-700">
                  Reset
                </button>
              </div>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label class="block text-xs font-medium text-gray-700 mb-1">From</label>
                  <input type="date" x-model="form.date_from" title="date_from"
                         class="w-full rounded-md border-gray-300 text-sm focus:ring-indigo-500 focus:border-indigo-500">
                </div>
                <div>
                  <label class="block text-xs font-medium text-gray-700 mb-1">To</label>
                  <input type="date" x-model="form.date_to" title="date_to"
                         class="w-full rounded-md border-gray-300 text-sm focus:ring-indigo-500 focus:border-indigo-500">
                </div>
              </div>
            </div>

            <!-- Actions -->
            <div class="pt-2">
              <button type="button" title="generate chart"
                      @click="loadChart()"
                      :disabled="loading"
                      class="w-full inline-flex justify-center items-center rounded-md bg-slate-700 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed">
                <template x-if="!loading">
                  <span>Generate chart</span>
                </template>
                <template x-if="loading">
                  <span>Loading…</span>
                </template>
              </button>

              <button type="button" title="download json"
                      @click="downloadJson()"
                      class="mt-2 w-full inline-flex justify-center items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">
                Download JSON
              </button>
            </div>

          </div>
        </div>
      </aside>

      <!-- Right: chart -->
      <section class="lg:col-span-8">
        <div class="bg-white rounded-lg shadow-sm border border-gray-200">
          <div class="px-5 py-4 border-b border-gray-200 flex items-center justify-between">
            <div>
              <h2 class="text-sm font-semibold text-gray-800">Preview</h2>
              <p class="text-xs text-gray-500" x-text="subtitle"></p>
            </div>

            <div class="flex gap-2">
              <button type="button"
                      @click="chartType='bar'; redraw()"
                      class="text-xs px-3 py-1 rounded border"
                      :class="chartType==='bar' ? 'bg-gray-900 text-white border-gray-900' : 'bg-white text-gray-700 border-gray-300'">
                Bar
              </button>
              <button type="button"
                      @click="chartType='line'; redraw()"
                      class="text-xs px-3 py-1 rounded border"
                      :class="chartType==='line' ? 'bg-gray-900 text-white border-gray-900' : 'bg-white text-gray-700 border-gray-300'">
                Line
              </button>
            </div>
          </div>

          <div class="p-5">
            <div class="relative">
              <canvas id="chartCanvas" height="120"></canvas>
            </div>

            <div class="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div class="rounded-md border border-gray-200 p-3">
                <div class="text-xs text-gray-500">Points</div>
                <div class="text-sm font-semibold text-gray-900" x-text="stats.points"></div>
              </div>
              <div class="rounded-md border border-gray-200 p-3">
                <div class="text-xs text-gray-500">Total</div>
                <div class="text-sm font-semibold text-gray-900" x-text="stats.total"></div>
              </div>
              <div class="rounded-md border border-gray-200 p-3">
                <div class="text-xs text-gray-500">Max</div>
                <div class="text-sm font-semibold text-gray-900" x-text="stats.max"></div>
              </div>
              <div class="rounded-md border border-gray-200 p-3">
                <div class="text-xs text-gray-500">Min</div>
                <div class="text-sm font-semibold text-gray-900" x-text="stats.min"></div>
              </div>
            </div>

            <div class="mt-4">
              <details class="rounded-md border border-gray-200 p-3">
                <summary class="cursor-pointer text-sm font-medium text-gray-800">Request payload</summary>
                <pre class="mt-2 text-xs text-gray-600 whitespace-pre-wrap" x-text="JSON.stringify(lastPayload, null, 2)"></pre>
              </details>
            </div>
          </div>
        </div>
      </section>

    </div>
  </div>
</main>

{% endblock %}

{% block extra-js %}


<script>
function chartsBuilder({ postUrl, csrfToken }) {
  return {
    postUrl,
    csrfToken,

    loading: false,
    message: '',
    messageType: 'success',

    chart: null,
    chartType: 'bar',
    subtitle: 'Choose options and generate.',

    lastPayload: {},
    lastResponse: { labels: [], data: [] },

    // main form state
    form: {
      x_axis: 'form_data.wilaya',
      y_axis: 'form_data.idadi_cal',
      agg: 'count',
      date_from: '',
      date_to: '',
    },

    // simple UI filters mapped to JSON keys
    filters: {},

    stats: { points: 0, total: 0, max: 0, min: 0 },

    init() {
      // auto-load default chart
      this.loadChart();
    },

    resetFilters() {
      this.form.date_from = '';
      this.form.date_to = '';
    },

    buildPayload() {
      const f = {};

      const payload = {
        x_axis: this.form.x_axis,
        agg: this.form.agg,
        y_axis: this.form.agg === 'count' ? null : this.form.y_axis,
        filters: f,
        date_from: this.form.date_from || null,
        date_to: this.form.date_to || null,
      };

      this.lastPayload = payload;
      return payload;
    },

    async loadChart() {
      // basic validation
      if (this.form.agg !== 'count' && !this.form.y_axis) {
        this.messageType = 'error';
        this.message = 'Please select a numeric Y-axis field for this aggregation.';
        return;
      }

      this.loading = true;
      this.message = '';
      this.subtitle = 'Loading chart data…';

      try {
        const payload = this.buildPayload();

        const res = await fetch(this.postUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': this.csrfToken,
          },
          body: JSON.stringify(payload)
        });

        const data = await res.json();
        if (!res.ok) {
          throw new Error(data.error || 'Request failed');
        }

        this.lastResponse = data;
        this.subtitle = `${data.agg.toUpperCase()} by ${data.x_axis}${data.y_axis ? (' → ' + data.y_axis) : ''}`;

        this.computeStats(data.data || []);
        this.draw(data.labels || [], data.data || []);

        this.messageType = 'success';
        this.message = 'Chart updated successfully.';
      } catch (err) {
        this.messageType = 'error';
        this.message = err.message || 'Failed to load chart.';
        this.subtitle = 'Error loading chart data.';
      } finally {
        this.loading = false;
      }
    },

    computeStats(arr) {
      const nums = (arr || []).map(v => Number(v || 0));
      const total = nums.reduce((a,b) => a + b, 0);
      const max = nums.length ? Math.max(...nums) : 0;
      const min = nums.length ? Math.min(...nums) : 0;

      this.stats = {
        points: nums.length,
        total: total,
        max: max,
        min: min,
      };
    },

    draw(labels, series) {
      const ctx = document.getElementById('chartCanvas');

      if (this.chart) {
        this.chart.destroy();
      }

      this.chart = new Chart(ctx, {
        type: this.chartType,
        data: {
          labels: labels,
          datasets: [{
            label: 'Value',
            data: series,
            backgroundColor: '#800000',   // ← maroon bars
            borderColor: '#660000',       // slightly darker border
            borderWidth: 1,
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: true,
          plugins: {
            legend: { display: false },
            tooltip: { enabled: true }
          },
          scales: {
            x: {
              ticks: { maxRotation: 0, autoSkip: true }
            },
            y: {
              beginAtZero: true
            }
          }
        }
      });
    },

    redraw() {
      // redraw with current response data without refetching
      this.draw(this.lastResponse.labels || [], this.lastResponse.data || []);
    },

    downloadJson() {
      const blob = new Blob([JSON.stringify(this.lastResponse, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'chart_data.json';
      a.click();
      URL.revokeObjectURL(url);
    }
  }
}
</script>
{% endblock extra-js %}

apps/projects/templates/surveys/data/instance.html
{% load form_tags %}

<div class=" pt-6 pb-20 px-10 inset-y-0 right-0 w-full h-full overflow-y-scroll overscroll-contain" id="detailContent">
    <div class="max-w-3xl space-y-4 mb-20">

        {% for group in jForm.pages %}
            
            {% if group.type == 'group' %}
                <div class="my-6 mb-10 border-b border-gray-200">
                    <h2 class=" text-blue-800">
                        {{ group.label }}
                    </h2>
                    {% for field in group.fields %}
                        {% for key, value in field.items %}
                        <div class="grid grid-cols-2 py-2">
                            <div class="text-sm">
                                {% if value.label %}
                                    {{ value.label }}
                                {% else %}
                                    {{ value.name|replace:"_, " }}
                                {% endif %}
                            </div>
                            <div class="text-sm">
                            {% with field_value=data|format_field_value:value %}
                                {% if field_value == True or field_value|lower == 'yes' %}
                                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800">
                                        Yes
                                    </span>
                                {% elif field_value == False or field_value|lower == 'no'%}
                                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium bg-red-100 text-red-800">
                                        No
                                    </span>
                                {% elif field_value == None or field_value == '' %}
                                    <span class="text-gray-400 italic">Not specified</span>
                                {% else %}
                                    {{ field_value }}
                                {% endif %}
                            {% endwith %}
                            </div>
                        </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
        {% endfor %}

    </div>

</div>

apps/projects/templates/surveys/data/map.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<main class="bg-white h-full">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">

        <!-- Card -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200">

            <!-- Card Header -->
            <div class="flex items-center justify-between px-5 py-4 border-b border-gray-200">
                <div>
                    <h2 class="text-sm font-semibold text-gray-800">
                        {{ title|default:'Data Map' }}
                    </h2>
                    <p class="text-xs text-gray-500">
                        Data maps
                    </p>
                </div>
            </div>

            <!-- Card Body -->
            <div class="flex flex-row flex-wrap">
                <div class="w-full p-4">
                    <div class="relative overflow-x-auto">
                        <div id="map" style="width: 100%; min-height:560px; height: auto;"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Card -->
    </div>
</main>

{% endblock %}

{% block extra-js %}
<script language="javascript">
    //create map
    const map = L.map('map').setView([-6.40177, 34.99269], 6);

    //create tileUrl and attribution
    const tileUrl = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png';
    const attribution = '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';

    //create tile
    const tile = L.tileLayer(tileUrl, {
        maxZoom: 19,
        attribution: attribution,
        id: 'mapbox/streets-v11'
    });

    //add tile to map
    tile.addTo(map);

    // 3. Fetch points from Django endpoint
    fetch("/projects/forms/points/" + "{{ cur_form.pk }}")
        .then(response => response.json())
        .then(points => {
            if (!Array.isArray(points)) return;

            const bounds = [];

            points.forEach(p => {
                if (typeof p.lat !== "number" || typeof p.lng !== "number") return;

                const marker = L.marker([p.lat, p.lng]).addTo(map);

                const popupHtml = `
                <strong>${p.title || 'No title'}</strong><br/>
                UUID: ${p.uuid || ''}<br/>
                Lat: ${p.lat.toFixed(5)}, Lng: ${p.lng.toFixed(5)}<br/>
                Created: ${p.created_at || ''}
            `;

                marker.bindPopup(popupHtml);
                bounds.push([p.lat, p.lng]);
            });

            // Zoom to fit all markers
            if (bounds.length > 0) {
                map.fitBounds(bounds, { padding: [20, 20] });
            }
        })
        .catch(err => {
            console.error("Error loading form points:", err);
        });

    // map signature
    map.attributionControl.addAttribution('Sacids Foundation for One Health&copy; <a href="#">Afyadata</a>');
</script>
{% endblock extra-js %}