apps/accounts/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import LogoutView, LoginView,  ChangePasswordView, ProfileView
from django.contrib.auth import views as auth_views

app_name = 'auth'

urlpatterns = [ 
    path("", LoginView.as_view() , name="login"),  
    path("login", LoginView.as_view() , name="login"),  
    path("logout", LogoutView.as_view(), name="logout"),
    path("profile", ProfileView.as_view(), name="profile"),
    path("change-password", ChangePasswordView.as_view(), name="change-password"),
 
]

apps/dashboard/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . views import DashboardView

app_name = 'dashboard'

urlpatterns = [ 
    path("summaries", DashboardView.as_view() , name="summaries"),  
 
]

apps/ohkr/urls.py
from django.urls import path
from . import views
from . import ajax_datatable_views

app_name = 'ohkr'

urlpatterns = [
    path('locations', views.LocationListView.as_view(), name='locations'),
    path('locations/sync', views.LocationSyncView.as_view(), name='locations.sync'),

    path('diseases', views.DiseaseListView.as_view(), name='diseases'),
    path('diseases/sync', views.DiseaseSyncView.as_view(), name='diseases.sync'),

    path('species', views.SpecieListView.as_view(), name='species'),
    path('species/sync', views.SpecieSyncView.as_view(), name='species.sync'),

    path('clinical-signs', views.ClinicalSignListView.as_view(), name='clinical-signs'),
    path('clinical-signs/sync', views.ClinicalSignSyncView.as_view(), name='clinical-signs.sync'),
    
    path('responses', views.ResponseListView.as_view(), name='responses'),

    #ajax datatable views
    path('locations-datatable', ajax_datatable_views.LocationAjaxDatatableView.as_view(), name="dt-locations"),
    path('diseases-datatable', ajax_datatable_views.DiseaseAjaxDatatableView.as_view(), name="dt-diseases"),
    path('species-datatable', ajax_datatable_views.SpecieAjaxDatatableView.as_view(), name="dt-species"),
    path('clinical-signs-datatable', ajax_datatable_views.ClinicalSignAjaxDatatableView.as_view(), name="dt-clinical-signs"),
    path('responses-datatable', ajax_datatable_views.ResponseAjaxDatatableView.as_view(), name="dt-responses"),
]

apps/projects/urls.py
from django.urls import path
from . import views, utils
from . import ajax_datatable_views

app_name = 'projects'

urlpatterns = [
    path('lists', views.ProjectListView.as_view(), name='lists'),
    path('show/<str:pk>', views.ProjectDetailView.as_view(), name='show'),
    path('create', views.ProjectCreateView.as_view(), name='create'),
    path('<str:pk>/edit', views.ProjectUpdateView.as_view(), name='edit'),
    path("<str:pk>/delete-confirm/", views.ProjectDeleteConfirmView.as_view(), name="delete-confirm"),
    path('<str:pk>/delete', views.ProjectDeleteView.as_view(), name='delete'),
    path('<str:pk>/activate', views.ProjectActivateView.as_view(), name='activate'),
    path('<str:pk>/data', views.ProjectDataView.as_view(), name='data'),

    # project members
    path('<str:pk>/members', views.ProjectMembersListView.as_view(), name='members'),

    # form management
    path('forms/<str:pk>', views.SurveyListView.as_view(), name='forms'),
    path('forms/<str:pk>/upload', views.SurveyCreateView.as_view(), name='upload-form'),
    path('forms/<str:pk>/edit', views.SurveyUpdateView.as_view(), name='edit-form'),
    path('forms/<str:pk>/delete', views.SurveyDeleteView.as_view(), name='delete-form'),
    path("forms/<str:pk>/definition", views.form_definition, name="form-definition"),

    # rules + OHKR
    path('forms/<str:pk>/attachments', views.SurveyAttachmentView.as_view(), name='form-attachments'),
    path('forms/<str:pk>/rules', views.SurveyRuleView.as_view(), name='form-rules'),

    # form data
    path('forms/<str:pk>/data', views.SurveyDataView.as_view(), name='form-data'),
    path('forms/<str:pk>/data/export', views.SurveyDataExportView.as_view(), name="form-data-export"),
    path('forms/<str:data_id>/data/instance', views.SurveyDataInstanceView.as_view(), name="form-data-instance"),

    path('forms/<str:pk>/data/charts', views.ChartsDataView.as_view(), name='form-data-charts'),
    path('forms/<str:pk>/data/map', views.MapDataView.as_view(), name='form-data-map'),
    path("forms/<str:form_id>/data/points", views.form_points, name="form-data-point"),

    #ajax datatable views
    path('projects-datatable', ajax_datatable_views.ProjectAjaxDatatableView.as_view(), name="dt-projects"),
    path('members-datatable/<str:pk>', ajax_datatable_views.MembersAjaxDatatableView.as_view(), name="dt-members"),
    path('forms-datatable/<str:pk>', ajax_datatable_views.FormsAjaxDatatableView.as_view(), name="dt-forms"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

import apps.accounts.urls
import apps.dashboard.urls
import apps.projects.urls
import apps.ohkr.urls
import apps.api.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(apps.accounts.urls)),
    path('auth/', include(apps.accounts.urls)),
    path('dashboard/', include(apps.dashboard.urls)),
    path('projects/', include(apps.projects.urls)),
    path('ohkr/', include(apps.ohkr.urls)),

    # API URL
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path("api/", include(apps.api.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/header.html
{% load static %}
<nav class="bg-white">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-12 items-center justify-between">
            <div class="flex items-center">
                <div class="flex-shrink-0">
                    <a href="{% url 'dashboard:summaries' %}">
                        <img class="block h-8 w-auto lg:hidden" src="{% static 'images/logo_C.png' %}" alt="Afyadata">
                    </a>

                    <a href="{% url 'dashboard:summaries' %}">
                        <img class="hidden h-8 w-auto lg:block" src="{% static 'images/logo_C.png' %}" alt="Afyadata">
                    </a>
                </div>
                <div class="hidden md:block">
                    <div class="ml-10 flex items-baseline space-x-4">
                        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                        <a href="{% url 'projects:lists' %}"
                            class="text-neutral-800 hover:bg-red-100 hover:rounded-md hover:text-slate-900 px-3 py-2 rounded-md text-sm font-medium">Projects</a>

                        <a href="{% url 'ohkr:diseases' %}"
                            class="text-neutral-800 hover:bg-red-100 hover:rounded-md hover:text-slate-900 px-3 py-2 rounded-md text-sm font-medium">OHKR</a>

                        <a href="#"
                            class="text-neutral-800 hover:bg-red-100 hover:rounded-md hover:text-slate-900 px-3 py-2 rounded-md text-sm font-medium">Users</a>

                        <a href="{% url 'projects:create' %}"
                            class="text-white bg-red-900 hover:bg-red-800 px-2 py-2 rounded-sm text-sm font-normal">
                            + Create Project
                        </a>
                    </div>
                </div>
            </div>

            <div class="hidden md:block">
                <div class="ml-4 flex items-center md:ml-6">
                    <button type="button"
                        class="rounded-full bg-white p-1 text-gray-600 hover:text-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-800 focus:ring-offset-2 focus:ring-offset-gray-800">
                        <span class="sr-only">View notifications</span>
                        <!-- Heroicon name: outline/bell -->
                        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                            stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                        </svg>
                    </button>

                    <!-- Profile dropdown -->
                    <div x-data="{dropdownMenu: false}" class="relative ml-3">
                        <div>
                            <button @click="dropdownMenu = ! dropdownMenu" type="button"
                                class="flex items-center focus:outline-none mr-3" id="user-menu-button"
                                aria-expanded="false" aria-haspopup="true">
                                <!-- <img class="w-8 h-8 rounded-full mr-4" src="{% static 'images/programmer.png' %}"
                                    alt="{{request.user.first_name}} {{request.user.last_name}}">  -->
                                    <span class="hidden md:inline-block text-sm">
                                        Hi, {{request.user.first_name}} {{request.user.last_name}}
                                    </span>
                                <svg class="pl-2 h-2" version="1.1" xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink"
                                    enable-background="new 0 0 129 129">
                                    <g>
                                        <path
                                            d="m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z" />
                                    </g>
                                </svg>
                            </button>
                        </div>

                        <!--
                      Dropdown menu, show/hide based on menu state.
      
                      Entering: "transition ease-out duration-100"
                        From: "transform opacity-0 scale-95"
                        To: "transform opacity-100 scale-100"
                      Leaving: "transition ease-in duration-75"
                        From: "transform opacity-100 scale-100"
                        To: "transform opacity-0 scale-95"
                    -->
                        <div x-show="dropdownMenu" @click.outside="dropdownMenu = false"
                            class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
                            role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                            <!-- Active: "bg-gray-100", Not Active: "" -->
                            <a href="#" class="block px-4 py-2 text-xs text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-0">MyProfile</a>

                            <a href="#" class="block px-4 py-2 text-xs text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-1">Change Password</a>

                            <a href="{% url 'auth:logout' %}" class="block px-4 py-2 text-xs text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-2">Logout</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="-mr-2 flex md:hidden">
                <!-- Mobile menu button -->
                <button type="button"
                    class="inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                    aria-controls="mobile-menu" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <!--
                    Heroicon name: outline/bars-3
      
                    Menu open: "hidden", Menu closed: "block"
                  -->
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                    <!--
                    Heroicon name: outline/x-mark
      
                    Menu open: "block", Menu closed: "hidden"
                  -->
                    <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
        <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'dashboard:summaries' %}"
                class="text-neutral-900 hover:bg-red-100 hover:rounded-md hover:text-slate-900 block px-3 py-2 rounded-md text-sm"
                aria-current="page">Dashboard</a>

            <a href="{% url 'projects:lists' %}"
                class="text-neutral-900 hover:bg-red-100 hover:rounded-md hover:text-slate-900 block px-3 py-2 rounded-md text-sm">Projects</a>

            <a href="#"
                class="text-neutral-900 hover:bg-red-100 hover:rounded-md hover:text-slate-900 block px-3 py-2 rounded-md text-sm">OHKR</a>

            <a href="{% url 'projects:create' %}"
                class="text-neutral-900 hover:bg-red-100 hover:rounded-md hover:text-slate-900 block px-3 py-2 rounded-md text-sm">Create
                Project</a>
        </div>
        <div class="border-t border-gray-100 pt-4 pb-3">
            <div class="flex items-center px-5">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        alt="">
                </div>
                <div class="ml-3">
                    <div class="text-sm font-medium leading-none text-gray-800">Tom Cook</div>
                    <div class="text-sm font-medium leading-none pt-2 text-gray-400">tom@example.com</div>
                </div>
                <button type="button"
                    class="ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                    <span class="sr-only">View notifications</span>
                    <!-- Heroicon name: outline/bell -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                    </svg>
                </button>
            </div>
            <div class="mt-3 space-y-1 px-2">
                <a href="#" class="block rounded-md px-3 py-2 text-sm text-gray-600 hover:bg-gray-700 hover:text-white">
                    My Profile
                </a>

                <a href="#" class="block rounded-md px-3 py-2 text-sm text-gray-600 hover:bg-gray-700 hover:text-white">
                    Change Password
                </a>

                <a href="#" class="block rounded-md px-3 py-2 text-sm text-gray-600 hover:bg-gray-700 hover:text-white">
                    Logout
                </a>
            </div>
        </div>
    </div>
</nav>

<header class="bg-slate-800">
    <div class="mx-auto max-w-7xl py-3 px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between">
            <!-- Title on the left -->
            <h1 class="text-xl font-medium tracking-tight text-white">
                {{ title|default:'Dashboard' }}
            </h1>

            <!-- Breadcrumb on the right -->
            <nav class="text-sm text-white">
                <!-- Example breadcrumb -->
                <ol class="flex space-x-1">
                    {% for crumb in breadcrumbs %}
                        <li>
                            {% if crumb.url %}
                                <a href="{{ crumb.url }}" class="font-normal text-xs hover:text-blue-500">{{ crumb.name }}</a>
                            {% else %}
                                <span class="font-normal text-xs text-gray-200">{{ crumb.name }}</span>
                            {% endif %}
                        </li>
                        {% if not forloop.last %}
                            <li>/</li>
                        {% endif %}
                    {% endfor %}
                </ol>
            </nav>
        </div>
    </div>
</header>

{% if links %}
<header class="bg-gray-700">
    <div class="mx-auto max-w-7xl py-0 px-4 sm:px-6">
        <div class="text-sm text-center text-white">
            <ul class="flex flex-wrap">
                {% for name, url in links.items %}
                <li>
                    <a href="{{ url }}"
                       class="inline-block py-2 px-3 font-normal text-sm border-b-2
                       {% if request.path == url %}
                           border-transparent text-orange-400 font-medium
                       {% else %}
                           border-transparent hover:text-orange-400
                       {% endif %}">
                        {{ name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</header>
{% endif %}