apps/ohkr/urls.py
from django.urls import path
from . import views
from . import ajax_datatable_views

app_name = 'ohkr'

urlpatterns = [
    path('locations', views.LocationListView.as_view(), name='locations'),
    path('locations/sync', views.LocationSyncView.as_view(), name='locations.sync'),

    path('diseases', views.DiseaseListView.as_view(), name='diseases'),
    path('diseases/sync', views.DiseaseSyncView.as_view(), name='diseases.sync'),

    path('species', views.SpecieListView.as_view(), name='species'),
    path('species/sync', views.SpecieSyncView.as_view(), name='species.sync'),

    path('clinical-signs', views.ClinicalSignListView.as_view(), name='clinical-signs'),
    path('clinical-signs/sync', views.ClinicalSignSyncView.as_view(), name='clinical-signs.sync'),
    
    path('responses', views.ResponseListView.as_view(), name='responses'),

    #ajax datatable views
    path('locations-datatable', ajax_datatable_views.LocationAjaxDatatableView.as_view(), name="dt-locations"),
    path('diseases-datatable', ajax_datatable_views.DiseaseAjaxDatatableView.as_view(), name="dt-diseases"),
    path('species-datatable', ajax_datatable_views.SpecieAjaxDatatableView.as_view(), name="dt-species"),
    path('clinical-signs-datatable', ajax_datatable_views.ClinicalSignAjaxDatatableView.as_view(), name="dt-clinical-signs"),
    path('responses-datatable', ajax_datatable_views.ResponseAjaxDatatableView.as_view(), name="dt-responses"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

import apps.accounts.urls
import apps.dashboard.urls
import apps.projects.urls
import apps.ohkr.urls
import apps.api.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(apps.accounts.urls)),
    path('auth/', include(apps.accounts.urls)),
    path('dashboard/', include(apps.dashboard.urls)),
    path('projects/', include(apps.projects.urls)),
    path('ohkr/', include(apps.ohkr.urls)),

    # API URL
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path("api/", include(apps.api.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ohkr/views.py
import json
import requests
import logging
import random
import string
from decouple import config
from datetime import datetime, date
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages

from django.db import transaction
from .models import *
from .utils import sync_locations

# Create your views here.
class LocationListView(generic.ListView):
    # permission_required = ''

    model = Location
    context_object_name = "locations"
    template_name = "locations/lists.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LocationListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(LocationListView, self).get_context_data(**kwargs)
        context["title"] = "Locations"
        context["page_title"] = "Locations"

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "OHKR", "url": reverse_lazy("ohkr:locations")},
            {"name": "Locations", "url": ""},
        ]

        # Add links to context
        context["links"] = {
            "Locations": reverse_lazy("ohkr:locations"),
            "Diseases": reverse_lazy("ohkr:diseases"),
            "Species": reverse_lazy("ohkr:species"),
            "Clinical Signs": reverse_lazy("ohkr:clinical-signs"),
            "Responses": reverse_lazy("ohkr:responses"),
        }

        return context


class LocationSyncView(generic.CreateView):
    """Pull locations from FAO RDS API and insert/update locally"""
    model = Location

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LocationSyncView, self).dispatch(*args, **kwargs)

    def get(self, *args, **kwargs):
        api_url = f"{config("FAO_BASE_URL")}/api/geographical_data/countries/TZA"
        headers = {"accept": "application/json"}

        try:
            # Fetch data from remote service
            response = requests.get(api_url, headers=headers, timeout=30)
            response.raise_for_status()
            remote_data = response.json()

            result = sync_locations(remote_data, source="RDS", active=True)
            print(result)

            # return response
            return JsonResponse(
                {
                    "success": True,
                    "success_msg": "Location synced",
                    # "created": created,
                    # "updated": updated,
                }
            )

        except requests.RequestException as e:
            return JsonResponse(
                {"success": False, "error_msg": f"Failed to sync location: {str(e)}"}
            )
        except Exception as e:
            return JsonResponse(
                {"success": False, "error_msg": str(e)},
            )


class DiseaseListView(generic.ListView):
    # permission_required = ''

    model = Disease
    context_object_name = "diseases"
    template_name = "diseases/lists.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DiseaseListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(DiseaseListView, self).get_context_data(**kwargs)
        context["title"] = "Diseases"
        context["page_title"] = "Diseases"

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "OHKR", "url": reverse_lazy("ohkr:diseases")},
            {"name": "Diseases", "url": ""},
        ]

        # Add links to context
        context["links"] = {
            "Locations": reverse_lazy("ohkr:locations"),
            "Diseases": reverse_lazy("ohkr:diseases"),
            "Species": reverse_lazy("ohkr:species"),
            "Clinical Signs": reverse_lazy("ohkr:clinical-signs"),
            "Responses": reverse_lazy("ohkr:responses"),
        }

        return context


class DiseaseSyncView(generic.CreateView):
    """Pull diseases from FAO RDS API and insert/update locally"""

    model = Disease

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DiseaseSyncView, self).dispatch(*args, **kwargs)

    def get(self, *args, **kwargs):
        api_url = f"{config("FAO_BASE_URL")}/api/diseases/"
        headers = {"accept": "application/json"}

        try:
            # Fetch data from remote service
            response = requests.get(api_url, headers=headers, timeout=30)
            response.raise_for_status()
            remote_data = response.json()

            created, updated = 0, 0
            with transaction.atomic():
                for item in remote_data["values"]:
                    obj, was_created = Disease.objects.update_or_create(
                        external_id=item["id"],
                        defaults={
                            "name": item["name"],
                            "source": "RDS",
                            "language_code": item["language_code"],
                        },
                    )
                    # increment created and updated
                    created += was_created
                    updated += not was_created

            # return response
            return JsonResponse(
                {
                    "success": True,
                    "success_msg": "Diseases synced",
                    "created": created,
                    "updated": updated,
                }
            )

        except requests.RequestException as e:
            return JsonResponse(
                {"success": False, "error_msg": f"Failed to sync diseases: {str(e)}"}
            )
        except Exception as e:
            return JsonResponse(
                {"success": False, "error_msg": str(e)},
            )


class SpecieListView(generic.ListView):
    # permission_required = ''

    model = Specie
    context_object_name = "species"
    template_name = "species/lists.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SpecieListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(SpecieListView, self).get_context_data(**kwargs)
        context["title"] = "Species"
        context["page_title"] = "Species"

        # breadcrumbs
        context["breadcrumbs"] = [
            {"name": "Dashboard", "url": reverse_lazy("dashboard:summaries")},
            {"name": "OHKR", "url": reverse_lazy("ohkr:diseases")},
            {"name": "Species", "url": ""},
        ]

        # Add links to context
        context["links"] = {
            "Locations": reverse_lazy("ohkr:locations"),
            "Diseases": reverse_lazy("ohkr:diseases"),
            "Species": reverse_lazy("ohkr:species"),
            "Clinical Signs": reverse_lazy("ohkr:clinical-signs"),
            "Responses": reverse_lazy("ohkr:responses"),
        }

        return context


class SpecieSyncView(generic.CreateView):
    """Pull species from FAO RDS  API and insert/update locally"""

    model = Disease

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SpecieSyncView, self).dispatch(*args, **kwargs)

    def get(self, *args, **kwargs):
        api_url = f"{config("FAO_BASE_URL")}/api/species/"
        headers = {"accept": "application/json"}

        try:
            # Fetch data from remote service
            response = requests.get(api_url, headers=headers, timeout=30)
            response.raise_for_status()
            remote_data = response.json()

            created, updated = 0, 0
            with transaction.atomic():
                for item in remote_data["values"]:
                    obj, was_created = Specie.objects.update_or_create(
                        external_id=item["id"],
                        defaults={
                            "name": item["name"],
                            "source": "RDS",
                            "language_code": item["language_code"],
                        },
                    )
                    # increment created and updated
                    created += was_created
                    updated += not was_created

            # return response
            return JsonResponse(
                {
                    "success": True,
                    "success_msg": "Species synced",
                    "created": created,
                    "updated": updated,
                }
            )

        except requests.RequestException as e:
            return JsonResponse(
                {"success": False, "error_msg": f"Failed to sync species: {str(e)}"}
            )
        except Exception as e:
            return JsonResponse(
                {"success": False, "error_msg": str(e)},
            )


class ClinicalSignListView(generic.ListView):
    # permission_required = ''

    model = ClinicalSign
    context_object_name = "clinical_signs"
    template_name = "clinical_signs/lists.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ClinicalSignListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ClinicalSignListView, self).get_context_data(**kwargs)
        context["title"] = "Clinical Signs"
        context["page_title"] = "Clinical Signs"

        # breadcrumbs
        context["breadcrumbs"] = [

apps/ohkr/templates/species/lists.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<main class="bg-white h-full" x-data="initData()">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">

        <!-- Card -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200">

            <!-- Card Header -->
            <div class="flex items-center justify-between px-5 py-4 border-b border-gray-200">
                <div>
                    <h2 class="text-sm font-semibold text-gray-800">
                        Species
                    </h2>
                    <p class="text-xs text-gray-500">
                        List of all species
                    </p>
                </div>

                <!-- Optional actions -->
                <div class="flex items-center space-x-2">
                    <button
                        class="inline-flex items-center rounded-sm border border-gray-300 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-100">
                        <i class='bx bxs-file-export px-1'></i> Export
                    </button>

                    <button type="button" x-html="btnSync" x-on:click="syncData();"
                        class="inline-flex items-center rounded-sm bg-slate-700 px-3 py-1.5 text-xs font-medium text-white hover:bg-slate-800">
                    </button>
                </div>
            </div>

            <!-- Card Body -->
            <div class="p-4">
                <div class="relative overflow-x-auto">
                    <div id="message_wrp" class="mb-3" hx-preserve></div>

                    <table id="datatable_species" class="w-full text-xs text-left text-gray-700 border-collapse">
                    </table>
                </div>
            </div>
        </div>
        <!-- End Card -->
    </div>
</main>

{% endblock %}

{% block extra-js %}

<script language="javascript">
    $(document).ready(function () {
        AjaxDatatableViewUtils.initialize_table(
            $('#datatable_species'),
            "{% url 'ohkr:dt-species' %}",
            {
                // extra_options (example)
                processing: false,
                autoWidth: false,
                scrollX: false,
                dom: `
                    <"flex justify-between items-center py-2 border-b text-sm"
                        <"flex gap-2 items-center"B>
                        <"flex items-center"p>
                    >
                    t
                `,
                buttons: [
                    // {
                    //     extend: 'csv',
                    //     text: 'Download Data',
                    //     filename: 'Project-Data-csv',
                    //     className: 'bg-gray-500 text-white text-xs px-3 py-1 rounded hover:bg-gray-600'
                    // }
                ],
                "pageLength": 13,
                responsive: false,
                language: {
                    search: "",
                    info: "_PAGE_ of _PAGES_",
                },
            }, {
            // extra_data
            // ...
        },);
    });

    //alpine data
    function initData() {
        return {
            formLoading: false,
            btnSync: "<i class='bx bxs-cloud-download px-1'></i> Sync Data",

            //show message
            showMessage(type, message) {
                const styles = {
                    success: "bg-green-100 border border-green-100 text-green-800 text-sm",
                    danger: "bg-red-100 border border-red-100 text-red-800 text-sm"
                };

                $('#message_wrp').html(
                    `<div class="${styles[type]} px-4 py-3 rounded-sm">${message}</div>`
                );
            },

            //sync diseases 
            async syncData() {
                this.formLoading = true;
                this.btnSync = "<i class='bx bx-loader-circle bx-spin'></i> Syncing data....";

                fetch(`/ohkr/species/sync`)
                    .then(response => response.json())
                    .then(data => {
                        if (data.success === true) {
                            this.showMessage('success', data.success_msg);
                            setTimeout(() => window.location.reload(), 3000);
                        } else if (data.success == false) {
                            this.showMessage('danger', data.error_msg)
                        }
                    }).catch(error => {
                        console.error("Error caught:", error);
                        this.showMessage('danger', data.error_msg);
                    }).finally(() => {
                        this.formLoading = false;
                        this.btnSync = "<i class='bx bxs-cloud-download px-1'></i> Sync Data";
                    });
            },
        }
    }

</script>
{% endblock extra-js %}